name: hls_dev

on:
  # run it on push to the default repository branch
  push:
    branches: [dev]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-docker-image-dev:
    runs-on: ubuntu-latest
    steps:
      - name: login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}
      - uses: actions/checkout@v2
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7
      - name: create image from repository
        run: docker build -t ghcr.io/axsddlr/r_homelabsales .
      - name: push image to GitHub Container Registry
        run: docker push ghcr.io/axsddlr/r_homelabsales:dev