name: hls

on:
  # run it on push to the default repository branch
  push:
    branches: [master]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}
      - uses: actions/checkout@v2
      - name: create image from repository
        run: docker build -t ${{ env.REGISTRY }}/axsddlr/${{ github.repository }} .
      - name: push image to GitHub Container Registry
        run: docker push ${{ env.REGISTRY }}/axsddlr/r_homelabsales:latest